baseURL = "https://blog.exploration5.games/"
languageCode = "en-us"
title = "The Adventures of Exploration #5"
theme = "xmin"

ignoreFiles = ["_template.md"]

preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# [permalinks]
#     post = "/post/:year/:month/:day/:slug/"
#     note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Games"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Come along with us for an Adventure"
    footer = "&copy; David Aronsohn 2017- | [Github](https://github.com/onlyhavecans) | [Twitter](https://twitter.com/onlyhavecans)"
